In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("netflix_titles.csv")

In [3]:
df.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5394,s5395,Movie,Hans Teeuwen: Real Rancour,Doesjka van Hoogdalem,Hans Teeuwen,Netherlands,"July 1, 2017",2018,TV-MA,86 min,Stand-Up Comedy,Comedian Hans Teeuwen rebels against political...
3529,s3530,Movie,Evelyn,Orlando von Einsiedel,NaN,United Kingdom,"September 10, 2019",2019,TV-MA,96 min,"Documentaries, International Movies","Haunted by the suicide of a brother, a directo..."
6171,s6172,Movie,Ant-Man and the Wasp,Peyton Reed,"Paul Rudd, Evangeline Lilly, Michael Douglas, ...",United States,"January 29, 2019",2018,PG-13,118 min,"Action & Adventure, Comedies, Sci-Fi & Fantasy","Problems big and small pop up when Scott Lang,..."
5715,s5716,TV Show,La Niña,NaN,"Ana María Estupiñán, Sebastian Eslava, Juan Se...",Colombia,"November 18, 2016",2016,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",A former Colombian guerrilla fighter faces cha...
6548,s6549,Movie,Dad,Gary David Goldberg,"Jack Lemmon, Ted Danson, Olympia Dukakis, Kath...",United States,"April 1, 2018",1989,PG,117 min,Dramas,Family bonds are revived after a father is dia...

In [4]:
df.shape

(8807, 12)

In [5]:
df.size

105684

In [6]:
df.index

RangeIndex(start=0, stop=8807, step=1)

In [7]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [8]:
df.drop(['show_id','description'],axis=1,inplace=True)

In [9]:
df.sample(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
5492,Movie,"Norm Macdonald: Hitler's Dog, Gossip & Trickery",Liz Plonka,Norm MacDonald,United States,"May 9, 2017",2017,TV-MA,61 min,Stand-Up Comedy
6454,Movie,Chauthi Koot,Gurvinder Singh,"Suvinder Vikky, Rajbir Kaur, Gurpreet Kaur Bha...","India, France","February 1, 2017",2015,TV-14,116 min,"Dramas, Independent Movies, International Movies"
232,TV Show,Wheel of Fortune,NaN,"Pat Sajak, Vanna White",United States,"August 25, 2021",2019,TV-G,3 Seasons,Reality TV
6667,Movie,Eh Janam Tumhare Lekhe,Harjit Singh,"Pavan Malhotra, Sudhanshu Aggarwal, Arjuna Bha...",India,"December 1, 2017",2015,TV-14,124 min,"Dramas, International Movies"
5402,Movie,The Invisible Guest,Paulo Oriol,"Mario Casas, Ana Wagener, José Coronado, Bárba...",Spain,"July 1, 2017",2016,TV-14,106 min,"International Movies, Thrillers"

In [10]:
df.isna().sum() # Checking count of null values in each Column

type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
dtype: int64

In [11]:
df["country"].value_counts().head(3) # Top 3 highest occuring countries

country
United States     2818
India              972
United Kingdom     419
Name: count, dtype: int64

In [12]:
mode_country = df["country"].mode()[0] # Highest Occuring State
mode_country

'United States'

In [13]:
df["country"] = df["country"].fillna(mode_country) # replacing country column null value to mode value of that column.

In [14]:
df["country"].isna().sum() # cross checking to make sure that changes happened.

np.int64(0)

In [15]:
mode_date = df["date_added"].mode()[0]
mode_date

'January 1, 2020'

In [16]:
df["date_added"] = df["date_added"].fillna(mode_date)

In [17]:
df["date_added"].isna().sum()

np.int64(0)

In [18]:
mode_rating = df["rating"].mode()[0]
mode_rating

'TV-MA'

In [19]:
df["rating"] = df["rating"].fillna(mode_rating)

In [20]:
df["rating"].isna().sum()

np.int64(0)

In [21]:
mode_duration = df["duration"].mode()[0]
mode_duration

'1 Season'

In [22]:
df["duration"] = df["duration"].fillna(mode_duration)
df["duration"].isna().sum()

np.int64(0)

In [23]:
df["director"] = df["director"].fillna("Not Mentioned") # Replacing null values with Default Value -- Not Mentioned

In [24]:
df["director"].isna().sum()

np.int64(0)

In [25]:
df["cast"] = df["cast"].fillna("Not Mentioned") # Relacing Null Values with Default Value
df["cast"].isna().sum()

np.int64(0)

In [52]:
df.isna().sum()

type            0
title           0
director        0
country         0
release_year    0
rating          0
duration        0
Year            0
Month           0
Day             0
Genre           0
Lead_actor      0
dtype: int64

In [28]:
df["rating"].unique() # checking the unique/distinct values in rating column

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'TV-Y7', 'R',
       'TV-G', 'G', 'NC-17', '74 min', '84 min', '66 min', 'NR',
       'TV-Y7-FV', 'UR'], dtype=object)

In [29]:
df = df[~df["rating"].str.contains("min")] # removing the wrong format rating rows
df["rating"].unique()

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'TV-Y7', 'R',
       'TV-G', 'G', 'NC-17', 'NR', 'TV-Y7-FV', 'UR'], dtype=object)

In [30]:
df["date_added"].unique()

array(['September 25, 2021', 'September 24, 2021', 'September 23, 2021',
       ..., 'December 6, 2018', 'March 9, 2016', 'January 11, 2020'],
      shape=(1766,), dtype=object)

In [31]:
df["date_added"] = df["date_added"].str.replace(",","") # replacing/removing the comma with blank in date_added Column 
df["date_added"].unique()

array(['September 25 2021', 'September 24 2021', 'September 23 2021', ...,
       'December 6 2018', 'March 9 2016', 'January 11 2020'],
      shape=(1766,), dtype=object)

In [32]:
df["date_added"] = pd.to_datetime(df["date_added"],format="mixed") # function to convert strings to datetime objects
df["date_added"].unique()

<DatetimeArray>
['2021-09-25 00:00:00', '2021-09-24 00:00:00', '2021-09-23 00:00:00',
 '2021-09-22 00:00:00', '2021-09-21 00:00:00', '2021-09-20 00:00:00',
 '2021-09-19 00:00:00', '2021-09-17 00:00:00', '2021-09-16 00:00:00',
 '2021-09-15 00:00:00',
 ...
 '2018-09-27 00:00:00', '2017-03-23 00:00:00', '2016-12-25 00:00:00',
 '2016-11-30 00:00:00', '2017-10-23 00:00:00', '2017-11-04 00:00:00',
 '2015-08-05 00:00:00', '2018-12-06 00:00:00', '2016-03-09 00:00:00',
 '2020-01-11 00:00:00']
Length: 1714, dtype: datetime64[ns]

In [33]:
pd.isnull(df).sum()

type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [34]:
df["Year"] = df["date_added"].dt.year # extracting year from a datetime column

In [35]:
df["Month"] = df["date_added"].dt.month # extracting month from a datetime column

In [36]:
df["Day"] = df["date_added"].dt.day # extracting day from a datetime column

In [37]:
df.sample(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,Year,Month,Day
8091,Movie,Still,"Chatchai Katenut, Manussa Vorasingha, Tanwarin...","Mai Charoenpura, Akara Amarttayakul, Supakson ...",Thailand,2018-09-14,2010,TV-MA,100 min,"Horror Movies, International Movies",2018,9,14
781,Movie,Black Holes | The Edge of All We Know,Peter Galison,Not Mentioned,United States,2021-06-02,2021,TV-14,99 min,Documentaries,2021,6,2
7552,Movie,Mythily Veendum Varunnu,Sabu Varghese,"Udhay, Kiran Raj, I.M. Vijayan, Sandhanam, Shi...",India,2018-08-01,2017,TV-PG,88 min,"Horror Movies, International Movies",2018,8,1
5404,TV Show,The Truth Seekers,Not Mentioned,"Chen Hanwei, Rebecca Lim, Desmond Tan, Yusuke ...",Singapore,2017-07-01,2016,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",2017,7,1
7378,Movie,Magnetic,Thierry Donard,"Tom Barrer, Liam Whaley, Wille Lindberg, Sam F...",France,2020-06-12,2018,TV-14,110 min,"Action & Adventure, Documentaries, Internation...",2020,6,12

In [38]:
df["Genre"] = df["listed_in"].str.split(",").str[0] # splitting the column using comma(,) and making a new column

In [51]:
df["Genre"].value_counts().head(5)

Genre
Dramas                      1592
Comedies                    1204
Action & Adventure           853
International TV Shows       743
Children & Family Movies     573
Name: count, dtype: int64

In [50]:
df.sample(5)

,type,title,director,country,release_year,rating,duration,Year,Month,Day,Genre,Lead_actor
1273,Movie,"Blue, Painful, Fragile",Shunsuke Kariyama,Japan,2020,TV-14,119 min,2021,2,24,International Movies,Ryo Yoshizawa
6488,Movie,City of God,"Fernando Meirelles, Katia Lund","Brazil, France, Germany",2002,R,130 min,2020,1,1,Dramas,Alexandre Rodrigues
445,Movie,The Beguiled,Sofia Coppola,United States,2017,R,94 min,2021,7,16,Dramas,Colin Farrell
3116,Movie,The Two Popes,Fernando Meirelles,"United Kingdom, Italy",2019,PG-13,126 min,2019,12,20,Dramas,Anthony Hopkins
1308,TV Show,Booba,Not Mentioned,United Kingdom,2021,TV-Y7,4 Seasons,2021,2,15,Kids' TV,Roman Karev

In [41]:
df = df[df["cast"] != "Not Mentioned"] # Removing rows where cast = Not Mentioned
df["cast"].value_counts()

cast
David Attenborough                                                                                                                                                         19
Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jigna Bhardwaj, Rajesh Kava, Mousam, Swapnil                                                                                    14
Samuel West                                                                                                                                                                10
Jeff Dunham                                                                                                                                                                 7
Michela Luci, Jamie Watson, Eric Peterson, Anna Claire Bartlam, Nicolas Aqui, Cory Doran, Julie Lemieux, Derek McGrath                                                      6
                                                                                                                                                                           ..
Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, Mansoor Alfeeli, Ahd                                                                                                          1
Mark Ruffalo, Jake Gyllenhaal, Robert Downey Jr., Anthony Edwards, Brian Cox, Elias Koteas, Donal Logue, John Carroll Lynch, Dermot Mulroney, Chloë Sevigny                 1
Jesse Eisenberg, Woody Harrelson, Emma Stone, Abigail Breslin, Amber Heard, Bill Murray, Derek Graf                                                                         1
Tim Allen, Courteney Cox, Chevy Chase, Kate Mara, Ryan Newman, Michael Cassidy, Spencer Breslin, Rip Torn, Kevin Zegers                                                     1
Luna Wedler, Jannis Niewöhner, Milan Peschel, Edin Hasanović, Anna Fialová, Marlon Boess, Victor Boccard, Fleur Geffrier, Aziz Dyab, Mélanie Fouché, Elizaveta Maximová     1
Name: count, Length: 7691, dtype: int64

In [43]:
df["Lead_actor"] = df["cast"].str.split(",").str[0] # Splitting the column by , and making a new column - Lead_actor
df["Lead_actor"].value_counts().head(5)

Lead_actor
Shah Rukh Khan        26
Akshay Kumar          23
Adam Sandler          20
Amitabh Bachchan      20
David Attenborough    20
Name: count, dtype: int64

In [49]:
df.sample(5)

,type,title,director,country,release_year,rating,duration,Year,Month,Day,Genre,Lead_actor
8210,Movie,The Bill Murray Stories: Life Lessons Learned ...,Tommy Avallone,United States,2018,TV-MA,72 min,2018,12,31,Documentaries,Tommy Avallone
142,Movie,Freedom Writers,Richard LaGravenese,"Germany, United States",2007,PG-13,124 min,2021,9,1,Dramas,Hilary Swank
8652,Movie,Ugly,Anurag Kashyap,India,2013,NR,125 min,2017,3,1,Dramas,Rahul Bhat
8603,Movie,Tomorrow Never Dies,Roger Spottiswoode,"United Kingdom, United States",1997,PG-13,119 min,2019,12,31,Action & Adventure,Pierce Brosnan
7686,Movie,Outlawed,"Adam Collins, Luke Radford",United Kingdom,2018,TV-MA,102 min,2019,2,15,Action & Adventure,Adam Collins

In [47]:
df.drop(["cast","date_added","listed_in"], axis=1, inplace=True) # Dropping the extra columns

KeyError: "['cast', 'date_added', 'listed_in'] not found in axis"

In [48]:
df.sample(5)

,type,title,director,country,release_year,rating,duration,Year,Month,Day,Genre,Lead_actor
3771,Movie,The Black Godfather,Reginald Hudlin,United States,2019,TV-MA,118 min,2019,6,7,Documentaries,Clarence Avant
5084,Movie,The Polka King,Maya Forbes,United States,2018,TV-14,94 min,2018,1,12,Comedies,Jack Black
5954,Movie,Even the Rain,Icíar Bollaín,"Spain, Mexico, France",2010,TV-MA,103 min,2011,5,17,Dramas,Luis Tosar
3696,TV Show,Record of Grancrest War,Not Mentioned,Japan,2018,TV-MA,1 Season,2019,7,1,Anime Series,Kentaro Kumagai
8682,Movie,Vizontele Tuuba,Yılmaz Erdoğan,Turkey,2004,NR,106 min,2017,3,10,Comedies,Yılmaz Erdoğan

In [53]:
df.to_csv("Transformed_data.csv")